# Generated by Django 3.0.5 on 2020-05-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='关联用户id')),
                ('decor_name', models.CharField(max_length=100, verbose_name='艺名')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('finish', models.SmallIntegerField(choices=[(0, '提早'), (1, '正常'), (2, '延迟')], default=1, verbose_name='如何完成')),
                ('is_firing', models.BooleanField(default=0, verbose_name='是否启动')),
                ('type', models.TextField(verbose_name='分类')),
                ('important', models.IntegerField(default=0, verbose_name='重要程度')),
                ('hurry', models.IntegerField(default=0, verbose_name='紧急程度')),
            ],
            options={
                'verbose_name': '计划',
                'verbose_name_plural': '计划',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='plan_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='关联用户id')),
                ('pj_id', models.IntegerField(verbose_name='关联项目id')),
                ('chapter', models.IntegerField(verbose_name='单元号')),
                ('section', models.TextField(verbose_name='小节名称')),
                ('title', models.TextField(verbose_name='任务标题')),
                ('detail', models.TextField(verbose_name='任务详细')),
                ('hover_tips', models.TextField(verbose_name='鼠标悬停提示')),
            ],
            options={
                'verbose_name': '计划细节',
                'verbose_name_plural': '计划细节',
                'db_table': 'plan_section',
            },
        ),
    ]
