# Generated by Django 3.0.5 on 2020-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200518_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_section',
            name='is_finished',
            field=models.BooleanField(null=True, verbose_name='是否已经完成'),
        ),
    ]
