# Generated by Django 3.0.5 on 2020-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_plan_section_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_section',
            name='is_finished',
            field=models.BooleanField(default=0, verbose_name='是否已经完成'),
        ),
    ]
