# Generated by Django 3.0.5 on 2020-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20200518_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='finish_cpt',
            field=models.IntegerField(null=True, verbose_name='最新完成章'),
        ),
        migrations.AddField(
            model_name='plan',
            name='finish_sct',
            field=models.IntegerField(null=True, verbose_name='最新完成节'),
        ),
    ]
