# Generated by Django 3.0.5 on 2020-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200519_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('plan_id', models.IntegerField(verbose_name='项目id')),
                ('finish_cpt', models.IntegerField(null=True, verbose_name='最新完成章')),
                ('finish_sct', models.IntegerField(null=True, verbose_name='最新完成节')),
                ('today_comment', models.TextField(null=True, verbose_name='今日评注')),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='finish_cpt',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='finish_sct',
        ),
    ]
