# Generated by Django 3.0.5 on 2020-05-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20200519_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_finish',
            options={'verbose_name': '计划完成记录', 'verbose_name_plural': '计划完成记录'},
        ),
        migrations.AlterModelTable(
            name='plan_finish',
            table='plan_finish',
        ),
    ]
