# Generated by Django 3.0.5 on 2020-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20200519_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_section',
            name='pj_name',
            field=models.TextField(null=True, verbose_name='关联项目名'),
        ),
    ]
