# Generated by Django 3.0.5 on 2020-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_plan_section_pj_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_section',
            name='pj_name',
            field=models.TextField(verbose_name='关联项目名'),
        ),
    ]
