# Generated by Django 3.0.5 on 2020-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20200519_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_section',
            name='review_times',
            field=models.IntegerField(default=0, verbose_name='复盘次数'),
        ),
    ]
