# Generated by Django 3.0.5 on 2020-05-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_plan_section_review_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_section',
            name='pj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
    ]
