# Generated by Django 3.0.5 on 2020-05-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_auto_20200522_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_section',
            old_name='pj_id',
            new_name='pj',
        ),
    ]
