# Generated by Django 3.0.5 on 2020-05-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20200522_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_section',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='plan_section',
            name='finish_end',
            field=models.DateField(null=True, verbose_name='完成时间段：结束'),
        ),
        migrations.AddField(
            model_name='plan_section',
            name='finish_start',
            field=models.DateField(null=True, verbose_name='完成时间段：开始'),
        ),
        migrations.AddField(
            model_name='plan_section',
            name='plan_status',
            field=models.BooleanField(choices=[(0, '未完成'), (1, '正在进行'), (2, '完成')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='plan_section',
            name='pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sections', to='plan.plan'),
        ),
    ]
