# Generated by Django 3.0.5 on 2020-05-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20200523_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_comment',
            options={'verbose_name': '计划评论', 'verbose_name_plural': '计划评论'},
        ),
        migrations.RemoveField(
            model_name='plan_comment',
            name='date',
        ),
        migrations.AddField(
            model_name='plan_comment',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='日期'),
        ),
    ]
