# Generated by Django 3.0.5 on 2020-05-23 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0017_auto_20200523_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_comment',
            old_name='finish_cpt',
            new_name='cpt',
        ),
        migrations.RenameField(
            model_name='plan_comment',
            old_name='finish_sct',
            new_name='sct',
        ),
        migrations.RemoveField(
            model_name='plan_comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='plan_comment',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan_comment',
            name='datetime',
            field=models.DateTimeField(verbose_name='日期'),
        ),
    ]
