# Generated by Django 3.0.5 on 2020-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20200523_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_section',
            name='finish_end',
            field=models.DateTimeField(null=True, verbose_name='完成时间段：结束'),
        ),
        migrations.AlterField(
            model_name='plan_section',
            name='finish_start',
            field=models.DateTimeField(null=True, verbose_name='完成时间段：开始'),
        ),
    ]
